spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/homework_manager?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 564820194
  thymeleaf:
    cache: false
logging:
  level:
    com.atBbgu.mapper: debug
